name: Build Synergy

# 使用 workflow_dispatch 来允许手动触发
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Synergy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest]  # ubuntu-latest
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'


    - name: Install dependencies
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
          choco install ninja
        fi
        
        if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
          python scripts/install_deps.py
        else
          ./scripts/install_deps.py
        fi

    - name: Configure build
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
          cmake -B build --preset=linux-release
        elif [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
          cmake -B build --preset=macos-release
        else
          cmake -B build --preset=windows-release
        fi
          
    - name: Build Synergy
      run: cmake --build build -j8
      
    - name: List build directory
      run: ls -la build/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: synergy-build
        path: |
          build/**/*.exe
          build/**/*.dmg
        if-no-files-found: warn


